ERROR [2019-02-01 10:40:14] H:\PyCharm 2018.3.2\LanhuSaas\framework\account\http.py 50 _http_request 10572 16192 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': '8PQdCfVUh9s9DlMIZkk8gVNuWWmMmjVFStUgHa3VvUA'} 
Traceback (most recent call last):
  File "H:\PyCharm 2018.3.2\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "H:\python27\lib\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "H:\python27\lib\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "H:\python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "H:\python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "H:\python27\lib\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=8PQdCfVUh9s9DlMIZkk8gVNuWWmMmjVFStUgHa3VvUA (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000005806E48>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',))
INFO [2019-02-01 10:40:14] H:\PyCharm 2018.3.2\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 10572 16192 
 	 验证用户登录token无效： 

ERROR [2019-02-01 14:43:49] H:\PyCharm 2018.3.2\LanhuSaas\framework\monitor\function.py 49 unit_show 14156 16396 
 	 请求作业模板失败：The user does not have permission to use this Business 

ERROR [2019-02-12 11:41:48] H:\PyCharm 2018.3.2\LanhuSaas\framework\monitor\function.py 49 unit_show 12600 9032 
 	 请求作业模板失败：The user does not have permission to use this Business 

ERROR [2019-02-13 10:23:30] H:\PyCharm 2018.3.2\LanhuSaas\framework\monitor\function.py 49 unit_show 6852 14640 
 	 请求作业模板失败：The user does not have permission to use this Business 

ERROR [2019-02-13 10:24:51] H:\PyCharm 2018.3.2\LanhuSaas\framework\monitor\function.py 49 unit_show 6852 13656 
 	 请求作业模板失败：The user does not have permission to use this Business 

