ERROR [2018-12-21 08:53:37] F:\Users\DeleMing\Desktop\Lanhu\framework\shell_app\function.py 86 show_host 704 15056 
 	 请求主机列表失败：An exception occurred while requesting CC interface, please contact the component developer to handle it. 

ERROR [2018-12-21 08:53:41] F:\Users\DeleMing\Desktop\Lanhu\framework\shell_app\function.py 86 show_host 704 15224 
 	 请求主机列表失败：An exception occurred while requesting CC interface, please contact the component developer to handle it. 

ERROR [2018-12-22 09:13:29] F:\Users\DeleMing\Desktop\Lanhu\framework\shell_app\function.py 87 show_host 14892 16564 
 	 请求主机列表失败：Component request third-party system [CC] interface [search_host] error: HTTPConnectionPool(host='cmdb-direct.service.consul', port=33031): Max retries exceeded with url: /api/v3/hosts/search (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd6131fea10>: Failed to establish a new connection: [Errno 111] Connection refused',)), please try again later or contact component developer to handle this 

ERROR [2019-01-04 10:29:06] E:\LanhuSaas\framework\account\http.py 50 _http_request 1056 11804 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x00000000058EEE48>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:29:06] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 1056 11804 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:29:20] E:\LanhuSaas\framework\account\http.py 50 _http_request 1056 2796 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000596EC18>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:29:20] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 1056 2796 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:29:33] E:\LanhuSaas\framework\account\http.py 50 _http_request 1056 7560 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000005A09940>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:29:33] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 1056 7560 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:54:45] E:\LanhuSaas\framework\account\http.py 50 _http_request 3996 2408 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x00000000058E0080>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:54:45] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 3996 2408 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:55:08] E:\LanhuSaas\framework\account\http.py 50 _http_request 11348 10628 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000005704F28>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:55:08] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 11348 10628 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:55:54] E:\LanhuSaas\framework\account\http.py 50 _http_request 11348 6068 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000000005763DA0>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:55:54] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 11348 6068 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:55:55] E:\LanhuSaas\framework\account\http.py 50 _http_request 11348 6712 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000578ACF8>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:55:55] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 11348 6712 
 	 验证用户登录token无效： 

ERROR [2019-01-04 10:56:11] E:\LanhuSaas\framework\account\http.py 50 _http_request 3764 10220 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc'} 
Traceback (most recent call last):
  File "E:\LanhuSaas\framework\account\http.py", line 38, in _http_request
    resp = requests.get(url=url, headers=headers, params=data)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\CY\AppData\Roaming\Python\Python27\site-packages\requests\adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='paas.blueking.com', port=8030): Max retries exceeded with url: /login/accounts/is_login/?bk_token=lrhekaEkal48MpMgS5rxlHZLvYi5eieKaOAHlKn9Qmc (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x000000000578AF28>: Failed to establish a new connection: [Errno 10061] ',))
INFO [2019-01-04 10:56:11] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 3764 10220 
 	 验证用户登录token无效： 

INFO [2019-01-04 11:12:13] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 2172 2816 
 	 验证用户登录token无效：Login validity is illegal 

ERROR [2019-01-04 11:12:21] E:\LanhuSaas\framework\account\http.py 56 _http_request 2172 9220 
 	 login http request error! type: GET, url: http://paas.blueking.com:8030/login/accounts/is_login/, data: {'bk_token': 'MRP_8Mt_sfoisL7LgAJFVuiV2dks-UmW1eidJMPCG4I'}, response_status_code: 500, response_content: 
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type"  

INFO [2019-01-04 11:12:21] E:\LanhuSaas\framework\account\accounts.py 91 verify_bk_login 2172 9220 
 	 验证用户登录token无效： 

